import Head from 'next/head';
import Image from 'next/image';
import Data from '../components/Zones';
import styles from '../styles/Home.module.css';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Waktu Solat</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Waktu Solat Malaysia</h1>
        <p className={styles.description}>Sila pilih zon.</p>
        <Data />
      </main>
    </div>
  );
}
