import Head from 'next/head';
import { Box } from '@mui/material';
import Data from '../components/Zones';

export default function Home() {
  return (
    <Box
      display='flex'
      flexDirection='column'
      flexGrow={1}
      padding='1rem'
      margin='0 auto'
      maxWidth='1200px'
    >
      <Head>
        <title>Waktu Solat</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <h1>Waktu Solat Malaysia</h1>
      <p>Sila pilih zon.</p>
      <Data />
    </Box>
  );
}
